# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='gender',
            field=models.CharField(choices=[('The patient is', 'The patient is'), ('M', 'Male'), ('F', 'Female')], default='The patient is', max_length=2),
        ),
    ]
