# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180207_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Identity',
            new_name='Patient',
        ),
    ]
