# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180207_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name']},
        ),
    ]
